[build]
  publish = "out"
  command = "yarn run deploy:ci"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
		X-Content-Type-Options = "nosniff"
		Referrer-Policy = "no-referrer"
		Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'https'"
		Feature-Policy = "geolocation 'none'; microphone 'none'; camera 'none'; gyroscope 'none';"
